name: Flutter Release Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cashe Flutter SDK
        uses: actions/cache@v4
	with:
	   path: flutter
	   key: flutter-sdk-stable
	
      - name: Cache Pub dependencies
	uses: 	action/cache@v4
	with:
	    path: ~/.pub-cache
	    key: pub-cache-$({ hashFiles('**/pubspec.lock' )})
	    restore-keys: pub-cache-
      
      -name: Cache Gradel
       uses: action/cache@v4
       with:
	  path: ~/.gradle
          key: gradel-cache-$({ runner.os })

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter (stable)
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b stable
          export PATH="$PWD/flutter/bin:$PATH"
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          flutter doctor
          flutter --version

      - name: Create .env file with secrets
        run: |
          cat << EOF > .env
          SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
          FACE_API_URL=${{ secrets.FACE_API_URL }}
          EOF

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk UCBS-Attendance-${{ github.ref_name }}.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: UCBS-Attendance-${{ github.ref_name }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
